"""Initial migration

Revision ID: 54f7fe629bfd
Revises:
Create Date: 2025-10-15 05:02:08.111449

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = "54f7fe629bfd"
down_revision = None
branch_labels = None
depends_on = None


def table_exists(table_name):
    """Check if a table exists in the database"""
    bind = op.get_bind()
    inspector = inspect(bind)
    return table_name in inspector.get_table_names()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not table_exists("events"):
        op.create_table(
            "events",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("title", sa.String(length=200), nullable=False),
            sa.Column("description", sa.Text(), nullable=True),
            sa.Column("date_time", sa.DateTime(), nullable=False),
            sa.Column("location", sa.String(length=200), nullable=True),
            sa.Column("attendees", sa.Text(), nullable=True),
            sa.Column("theme", sa.String(length=50), nullable=True),
            sa.Column("link", sa.String(length=500), nullable=True),
            sa.Column(
                "created_at",
                sa.DateTime(),
                server_default=sa.text("now()"),
                nullable=True,
            ),
            sa.Column(
                "updated_at",
                sa.DateTime(),
                server_default=sa.text("now()"),
                nullable=True,
            ),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(op.f("ix_events_id"), "events", ["id"], unique=False)

    if not table_exists("hobbies"):
        op.create_table(
            "hobbies",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("name", sa.String(length=100), nullable=False),
            sa.Column("category", sa.String(length=50), nullable=True),
            sa.Column("description", sa.Text(), nullable=True),
            sa.Column(
                "created_at",
                sa.DateTime(),
                server_default=sa.text("now()"),
                nullable=True,
            ),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("name"),
        )
        op.create_index(op.f("ix_hobbies_id"), "hobbies", ["id"], unique=False)

    if not table_exists("skills"):
        op.create_table(
            "skills",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("name", sa.String(length=100), nullable=False),
            sa.Column("category", sa.String(length=50), nullable=True),
            sa.Column("description", sa.Text(), nullable=True),
            sa.Column(
                "created_at",
                sa.DateTime(),
                server_default=sa.text("now()"),
                nullable=True,
            ),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("name"),
        )
        op.create_index(op.f("ix_skills_id"), "skills", ["id"], unique=False)

    if not table_exists("startups"):
        op.create_table(
            "startups",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("name", sa.String(length=100), nullable=False),
            sa.Column("description", sa.Text(), nullable=True),
            sa.Column("industry", sa.String(length=100), nullable=True),
            sa.Column("stage", sa.String(length=50), nullable=True),
            sa.Column("website_url", sa.String(length=200), nullable=True),
            sa.Column("target_market", sa.String(length=200), nullable=True),
            sa.Column("revenue_arr", sa.String(length=100), nullable=True),
            sa.Column(
                "created_at",
                sa.DateTime(),
                server_default=sa.text("now()"),
                nullable=True,
            ),
            sa.Column(
                "updated_at",
                sa.DateTime(),
                server_default=sa.text("now()"),
                nullable=True,
            ),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(op.f("ix_startups_id"), "startups", ["id"], unique=False)

    if not table_exists("founders"):
        op.create_table(
            "founders",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("name", sa.String(length=100), nullable=False),
            sa.Column("email", sa.String(length=100), nullable=False),
            sa.Column("bio", sa.Text(), nullable=True),
            sa.Column("location", sa.String(length=100), nullable=True),
            sa.Column("linkedin_url", sa.String(length=200), nullable=False),
            sa.Column("twitter_url", sa.String(length=200), nullable=True),
            sa.Column("github_url", sa.String(length=200), nullable=True),
            sa.Column("profile_image_url", sa.String(length=500), nullable=True),
            sa.Column("profile_visible", sa.Boolean(), nullable=False),
            sa.Column("auth0_user_id", sa.String(length=100), nullable=True),
            sa.Column("startup_id", sa.Integer(), nullable=True),
            sa.Column(
                "created_at",
                sa.DateTime(),
                server_default=sa.text("now()"),
                nullable=True,
            ),
            sa.Column(
                "updated_at",
                sa.DateTime(),
                server_default=sa.text("now()"),
                nullable=True,
            ),
            sa.ForeignKeyConstraint(
                ["startup_id"],
                ["startups.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("auth0_user_id"),
            sa.UniqueConstraint("email"),
        )
        op.create_index(op.f("ix_founders_id"), "founders", ["id"], unique=False)

    if not table_exists("founder_hobbies"):
        op.create_table(
            "founder_hobbies",
            sa.Column("founder_id", sa.Integer(), nullable=False),
            sa.Column("hobby_id", sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(
                ["founder_id"],
                ["founders.id"],
            ),
            sa.ForeignKeyConstraint(
                ["hobby_id"],
                ["hobbies.id"],
            ),
            sa.PrimaryKeyConstraint("founder_id", "hobby_id"),
        )

    if not table_exists("founder_skills"):
        op.create_table(
            "founder_skills",
            sa.Column("founder_id", sa.Integer(), nullable=False),
            sa.Column("skill_id", sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(
                ["founder_id"],
                ["founders.id"],
            ),
            sa.ForeignKeyConstraint(
                ["skill_id"],
                ["skills.id"],
            ),
            sa.PrimaryKeyConstraint("founder_id", "skill_id"),
        )

    if not table_exists("help_requests"):
        op.create_table(
            "help_requests",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("founder_id", sa.Integer(), nullable=False),
            sa.Column("title", sa.String(length=200), nullable=False),
            sa.Column("description", sa.Text(), nullable=False),
            sa.Column("category", sa.String(length=50), nullable=True),
            sa.Column("urgency", sa.String(length=20), nullable=True),
            sa.Column("status", sa.String(length=20), nullable=True),
            sa.Column(
                "created_at",
                sa.DateTime(),
                server_default=sa.text("now()"),
                nullable=True,
            ),
            sa.Column(
                "updated_at",
                sa.DateTime(),
                server_default=sa.text("now()"),
                nullable=True,
            ),
            sa.ForeignKeyConstraint(
                ["founder_id"],
                ["founders.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(
            op.f("ix_help_requests_id"), "help_requests", ["id"], unique=False
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_help_requests_id"), table_name="help_requests")
    op.drop_table("help_requests")
    op.drop_table("founder_skills")
    op.drop_table("founder_hobbies")
    op.drop_index(op.f("ix_founders_id"), table_name="founders")
    op.drop_table("founders")
    op.drop_index(op.f("ix_startups_id"), table_name="startups")
    op.drop_table("startups")
    op.drop_index(op.f("ix_skills_id"), table_name="skills")
    op.drop_table("skills")
    op.drop_index(op.f("ix_hobbies_id"), table_name="hobbies")
    op.drop_table("hobbies")
    op.drop_index(op.f("ix_events_id"), table_name="events")
    op.drop_table("events")
    # ### end Alembic commands ###
